# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='programme_id',
            field=models.CharField(blank=True, help_text='Programme ID for Astro TV broadcast.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=models.CharField(help_text='Description for the event. Maximum 1000 words', max_length=1000),
        ),
    ]
