# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('events', '0004_auto_20170609_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTwitchRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_twitch_relationship', to='events.EventPage')),
                ('twitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_event_relationship', to='base.TwitchChannel')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
