# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170623_0646'),
        ('events', '0005_eventtwitchrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventYoutubeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_youtube_relationship', to='events.EventPage')),
                ('youtube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_event_relationship', to='base.YoutubeChannel')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
