# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('base', '0003_author'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepeoplerelationship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_article_relationship', to='base.Author'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_banner', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='thumbnail_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_thumbnail_banner', to='wagtailimages.Image'),
        ),
    ]
