# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 03:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170619_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='test',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())], null=True),
        ),
    ]
