# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlepage_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='test',
        ),
    ]
