# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_articlepage_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='publish_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date Article Published'),
        ),
    ]
