# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 10:36
from __future__ import unicode_literals

import base.blocks.custom_blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20170921_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('captioned_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), (b'alignment', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('centered', 'Centered'), ('stretched', 'Stretched (within panel margins)'), ('full-width', 'Full width (covering panel margins)'), ('left-aligned', 'Left aligned'), ('left-aligned-float', 'Left aligned + word wrap'), ('right-aligned', 'Right aligned'), ('right-aligned-float', 'Right aligned + word wrap')])), (b'max_width', wagtail.wagtailcore.blocks.IntegerBlock(required=False)), (b'caption', wagtail.wagtailcore.blocks.CharBlock(max_length=200, required=False))], label='Image')), ('authored_block_quote', wagtail.wagtailcore.blocks.StructBlock([(b'quote', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), (b'author', wagtail.wagtailcore.blocks.CharBlock(label='Author (optional)', max_length=200, required=False))], label='Block Quote')), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(label='Raw HTML')), ('clearfix', base.blocks.custom_blocks.ClearfixBlock())], null=True),
        ),
    ]
