# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20171009_1836'),
    ]

    operations = [
        migrations.RenameField(
            'ArticlePage',
            'thumbnail_banner',
            'thumbnail'
        ),
    ]
