# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170630_0918'),
        ('home', '0004_auto_20170703_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test_live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_live_youtube', to='base.YoutubeChannel'),
        ),
    ]
