# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_test_live'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='test_live',
            new_name='live_youtube_channel',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='live_youtube_id',
        ),
    ]
