# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('programme', '0003_auto_20170721_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_thumbnail', to='wagtailimages.Image'),
        ),
    ]
