# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_programmepage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short Description to be displayed at the top of the page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='programmepage',
            name='tv_rating',
            field=models.CharField(blank=True, help_text='i.e. PG13, SX18', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='air_time',
            field=models.CharField(blank=True, help_text='Duration of Each Episode', max_length=200, null=True),
        ),
    ]
