# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_auto_20170725_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmepage',
            name='tv_rating',
            field=models.CharField(blank=True, help_text='Malaysian Standard: U, P13, 18', max_length=50, null=True),
        ),
    ]
