# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 10:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0010_auto_20170926_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('captioned_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), (b'alignment', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('centered', 'Centered'), ('stretched', 'Stretched (within panel margins)'), ('full-width', 'Full width (covering panel margins)'), ('left-aligned', 'Left aligned'), ('left-aligned-float', 'Left aligned + word wrap'), ('right-aligned', 'Right aligned'), ('right-aligned-float', 'Right aligned + word wrap')])), (b'max_width', wagtail.wagtailcore.blocks.IntegerBlock(required=False)), (b'caption', wagtail.wagtailcore.blocks.CharBlock(max_length=200, required=False))], label='Image')), ('block_quote', wagtail.wagtailcore.blocks.BlockQuoteBlock(label='Block Quote')), ('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(label='Raw HTML'))], null=True),
        ),
    ]
