# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 10:16
from __future__ import unicode_literals

import base.blocks.custom_blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0012_auto_20171012_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'ol', 'ul', 'hr'])), ('captioned_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), (b'alignment', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('centered', 'Centered'), ('left-aligned', 'Left aligned'), ('left-aligned-float', 'Left aligned + word wrap'), ('right-aligned', 'Right aligned'), ('right-aligned-float', 'Right aligned + word wrap')])), (b'width', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('original', 'Original width'), ('width-100', '100% stretched'), ('width-33', '33% stretched'), ('width-50', '50% stretched'), ('width-150', '150% stretched'), ('width-full-page', 'Full page stretch')])), (b'hyperlink', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'caption', wagtail.wagtailcore.blocks.CharBlock(max_length=200, required=False))], label='Image')), ('authored_block_quote', wagtail.wagtailcore.blocks.StructBlock([(b'quote', wagtail.wagtailcore.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'ol', 'ul', 'hr'], required=True)), (b'author', wagtail.wagtailcore.blocks.CharBlock(label='Author (optional)', max_length=200, required=False))], label='Block Quote')), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(label='Raw HTML')), ('clearfix', base.blocks.custom_blocks.ClearfixBlock())], null=True),
        ),
    ]
