# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(help_text='Verbose of the Channel', max_length=254)),
                ('channel_name', models.CharField(help_text='Channel name appearing at the last section of the url', max_length=100)),
            ],
            options={
                'verbose_name': 'Twitch Channel',
                'verbose_name_plural': 'Twitch Channels',
            },
        ),
    ]
