# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='uploaded_by_user',
        ),
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='image',
        ),
        migrations.DeleteModel(
            name='CustomImage',
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
    ]
