# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170620_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchannel',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
