# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_twitchchannel_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(help_text='Verbose Name of the Channel', max_length=254)),
                ('channel_id', models.CharField(help_text='Channel id', max_length=100)),
                ('subscribe', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Youtube Channel',
                'verbose_name_plural': 'Youtube Channels',
            },
        ),
        migrations.AlterField(
            model_name='twitchchannel',
            name='channel_title',
            field=models.CharField(help_text='Verbose Name of the Channel', max_length=254),
        ),
    ]
