# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170623_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='Game Genre', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
