# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_gamegenre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamegenre',
            options={'verbose_name': 'Game Genre', 'verbose_name_plural': 'Game Genres'},
        ),
    ]
