# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170630_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nick_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Nickname'),
        ),
    ]
