# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20170926_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nick_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Nick name'),
        ),
    ]
